jobs:
- job: iOS

  pool:
    vmImage: macOS-13

  variables:
    - name: NUGET_PACKAGES
      value: $(build.sourcesdirectory)/.nuget
    - name: VersionCodeOffset
      value: 400559 # last value for the APK release
    - group: unoplatform.apple.ios.appstore.distribution

  workspace:
     clean: all

  steps:

  - template: build/uno-ci/dotnet-install-mac.yml
  - template: build/uno-ci/canary-updater.yml
  - template: build/uno-ci/gitversion.yml
  - template: build/uno-ci/jdk-setup.yml

  - task: InstallAppleCertificate@2
    displayName: Install Certificate
    inputs:
      certSecureFile: UnoPlatform-Apple-Distribution.p12
      certPwd: $(appleappstorecertificatepassword)
      keychain: temp

  - task: InstallAppleProvisioningProfile@1
    displayName: Install Provisioning Profile
    inputs:
      provisioningProfileLocation: secureFiles
      provProfileSecureFile: Uno_Calculator.mobileprovision

  - task: InstallAppleProvisioningProfile@1
    displayName: Install Provisioning Profile (Canary)
    inputs:
      provisioningProfileLocation: secureFiles
      provProfileSecureFile: Uno_Calculator_Canary_iOS.mobileprovision

  - bash: |
      cd $(build.sourcesdirectory)/src/CalcManager
      chmod +x build_ios.sh
      ./build_ios.sh

    displayName: Build native CalcManager

  - task: MSBuild@1
    inputs:
      solution: '$(build.sourcesdirectory)/src/build/build.csproj'
      msbuildLocationMethod: version
      msbuildVersion: latest
      msbuildArchitecture: x86
      msbuildArguments: /r  /p:BuildPlatformTarget=iOS /bl:$(build.artifactstagingdirectory)/build.binlog 
      clean: false
      maximumCpuCount: true
      restoreNugetPackages: false
      logProjectEvents: true
      createLogFile: true

  - bash: |
      cd $(build.sourcesdirectory)/src/Calculator.mobile
      dotnet publish -f net8.0-ios -c Release /p:ArchiveOnBuild=true /bl:$(build.artifactstagingdirectory)/build-netcore.binlog "/p:InformationalVersion=$GITVERSION_INFORMATIONALVERSION"

    displayName: 'Build iOS Binaries (netcore)'

  - task: CopyFiles@2
    displayName: 'Publish iOS Binaries (netcore)'
    inputs:
      SourceFolder: $(build.sourcesdirectory)/src/Calculator.Mobile/bin/Release/net8.0-ios
      Contents:  |
        **/*.ipa
        **/*.dSym/**
      TargetFolder: $(build.artifactstagingdirectory)
      CleanTargetFolder: false
      OverWrite: false
      flattenFolders: false

  - task: PublishBuildArtifacts@1
    condition: always()
    retryCountOnTaskFailure: 3
    inputs:
      PathtoPublish: $(build.artifactstagingdirectory)
      ArtifactName: Uno-Calculator-iOS
      ArtifactType: Container
